import {
  IconBrandGithub,
  IconBrandInstagram,
  IconBrandLeetcode,
  IconBrandLinkedin,
  IconBrandYoutube,
} from "@tabler/icons-react";
const Info = {
  name: "Arun Kumar Suthari",
  stack: [
    "App Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Competitive Programmer",
    "Machine Learning Enthusiast",
  ],
  bio: "I'm a software engineer with a strong foundation in computer science and problem-solving, currently working as an Application Developer at Oracle. With a background in mechanical engineering and a CSE minor, I bring a multidisciplinary approach to building robust, scalable applications. I specialize in full-stack development, data structures and algorithms, and crafting clean, efficient code for enterprise-grade solutions. Always open to discussing innovative ideas and tech collaborations — let’s connect and build something impactful.",
};

const ProjectInfo = [
  {
    title: "Will add soon",
    desc: "Ekart is a modern, fully responsive e-commerce platform built using React, TailwindCSS, Heroicons, and HeadlessUI, offering a seamless shopping experience across all devices. It features secure user authentication with login, registration, and logout functionalities. Users can add items to a wishlist or remove them, search for specific products, and add them to a shopping cart for purchase. The checkout process includes form validation for address and payment information, ensuring accuracy and security. After purchase, users can view their order history in the Orders section. Ekart combines robust functionality with a sleek, intuitive design, making online shopping effortless and enjoyable.",
    image: "ekart.png",
    live: true,
    technologies: ["React", "Tailwind", "Redux", "Heroicons", "HeadlessUI"],
    link: "https://code-mars.github.io/Ekart/",
    github: "https://github.com/Code-Mars/Ekart/",
  },
  {
    title: "Will add soon",
    desc: "Ekart is a modern, fully responsive e-commerce platform built using React, TailwindCSS, Heroicons, and HeadlessUI, offering a seamless shopping experience across all devices. It features secure user authentication with login, registration, and logout functionalities. Users can add items to a wishlist or remove them, search for specific products, and add them to a shopping cart for purchase. The checkout process includes form validation for address and payment information, ensuring accuracy and security. After purchase, users can view their order history in the Orders section. Ekart combines robust functionality with a sleek, intuitive design, making online shopping effortless and enjoyable.",
    image: "ekart.png",
    live: true,
    technologies: ["React", "Tailwind", "Redux", "Heroicons", "HeadlessUI"],
    link: "https://code-mars.github.io/Ekart/",
    github: "https://github.com/Code-Mars/Ekart/",
  },
  {
    title: "Will add soon",
    desc: "Ekart is a modern, fully responsive e-commerce platform built using React, TailwindCSS, Heroicons, and HeadlessUI, offering a seamless shopping experience across all devices. It features secure user authentication with login, registration, and logout functionalities. Users can add items to a wishlist or remove them, search for specific products, and add them to a shopping cart for purchase. The checkout process includes form validation for address and payment information, ensuring accuracy and security. After purchase, users can view their order history in the Orders section. Ekart combines robust functionality with a sleek, intuitive design, making online shopping effortless and enjoyable.",
    image: "ekart.png",
    live: true,
    technologies: ["React", "Tailwind", "Redux", "Heroicons", "HeadlessUI"],
    link: "https://code-mars.github.io/Ekart/",
    github: "https://github.com/Code-Mars/Ekart/",
  },
  {
    title: "Will add soon",
    desc: "Ekart is a modern, fully responsive e-commerce platform built using React, TailwindCSS, Heroicons, and HeadlessUI, offering a seamless shopping experience across all devices. It features secure user authentication with login, registration, and logout functionalities. Users can add items to a wishlist or remove them, search for specific products, and add them to a shopping cart for purchase. The checkout process includes form validation for address and payment information, ensuring accuracy and security. After purchase, users can view their order history in the Orders section. Ekart combines robust functionality with a sleek, intuitive design, making online shopping effortless and enjoyable.",
    image: "ekart.png",
    live: true,
    technologies: ["React", "Tailwind", "Redux", "Heroicons", "HeadlessUI"],
    link: "https://code-mars.github.io/Ekart/",
    github: "https://github.com/Code-Mars/Ekart/",
  },
  {
    title: "Will add soon",
    desc: "Ekart is a modern, fully responsive e-commerce platform built using React, TailwindCSS, Heroicons, and HeadlessUI, offering a seamless shopping experience across all devices. It features secure user authentication with login, registration, and logout functionalities. Users can add items to a wishlist or remove them, search for specific products, and add them to a shopping cart for purchase. The checkout process includes form validation for address and payment information, ensuring accuracy and security. After purchase, users can view their order history in the Orders section. Ekart combines robust functionality with a sleek, intuitive design, making online shopping effortless and enjoyable.",
    image: "ekart.png",
    live: true,
    technologies: ["React", "Tailwind", "Redux", "Heroicons", "HeadlessUI"],
    link: "https://code-mars.github.io/Ekart/",
    github: "https://github.com/Code-Mars/Ekart/",
  },
  // {
  //   title: "Facebook Clone",
  //   desc: "Facebook Clone is a full-stack web application that replicates the core features of Facebook, including user authentication, posting, and commenting. The front end is built with React, TailwinCSS, Tabler-Icons, Mantine and Firebase, while the back end uses Firebase for user authentication and data storage. Users can create an account, log in, post updates, and comment on posts. The app features real-time updates, so users can see new comments as they are posted. Facebook Clone provides a seamless user experience with a clean, modern design and intuitive functionality.",
  //   image: "Facebook.png",
  //   live: false,
  //   technologies: [
  //     "React",
  //     "Springboot",
  //     "MongoDB",
  //     "Tailwind",
  //     "Tabler-Icons",
  //     "Firebase",
  //   ],
  //   link: "https://github.com/Code-Mars/Facebook-Clone",
  //   github: "https://github.com/Code-Mars/Facebook-Clone",
  // },
  // {
  //   title: "Spotify Clone",
  //   desc: "Spotify Clone is a full-stack web application that replicates the core features of Spotify, including user authentication, music playback, and playlist creation. The front end is built with React, TailwindCSS, Heroicons, and Firebase, while the back end uses Firebase for user authentication and data storage. Users can create an account, log in, search for songs, and create playlists. The app features real-time updates, so users can see new songs as they are added. Spotify Clone provides a seamless user experience with a clean, modern design and intuitive functionality.",
  //   image: "Spotify.png",
  //   live: false,
  //   technologies: [
  //     "React",
  //     "Springboot",
  //     "Tailwind",
  //     "Tabler-Icons",
  //     "MongoDB",
  //     "Firebase",
  //   ],
  //   link: "https://github.com/Code-Mars/Spotify-Clone",
  //   github: "https://github.com/Code-Mars/Spotify-Clone",
  // },
  // {
  //   title: "Travel Tracker",
  //   desc: "Travel Tracker is a full-stack web application that allows users to track their travel experiences and share them with others. The front end is built with React, Bootstrap, while the back end uses Node.js, Express, and PostgresSQL. Users can create an account, log in, add new trips, and view their past trips on a map. The app features a clean, modern design with interactive maps and a user-friendly interface. Travel Tracker combines functionality with style, making it easy and enjoyable to record and share travel memories.",
  //   image: "Travel.png",
  //   live: false,
  //   technologies: ["React", "Node.js", "PostgresSQL", "Express", "Bootstrap"],
  //   link: "https://github.com/Code-Mars/Travel-Tracker",
  //   github: "https://github.com/Code-Mars/Travel-Tracker",
  // },
  // {
  //   title: "Instagram Clone",
  //   desc: "Instagram Clone is a full-stack web application that replicates the core features of Instagram, including user authentication, image uploading, and commenting. The front end is built with React, TailwindCSS, and Heroicons, while the back end uses Firebase for user authentication and image storage. Users can create an account, log in, upload images, and comment on posts. The app features real-time updates, so users can see new comments as they are posted. Instagram Clone provides a seamless user experience with a clean, modern design and intuitive functionality.",
  //   image: "Instagram.png",
  //   live: false,
  //   technologies: [
  //     "React",
  //     "Springboot",
  //     "Tailwind",
  //     "Heroicons",
  //     "Firebase",
  //     "MongoDB",
  //   ],
  //   link: "https://github.com/Code-Mars/Instagram-Clone",
  //   github: "https://github.com/Code-Mars/Instagram-Clone",
  // },
  // {
  //   title: "CodeX Code Editor",
  //   desc: "CodeX is a modern, fully responsive code editor built using React, TailwindCSS, and Ace Editor, offering a seamless coding experience across all devices. It features syntax highlighting for popular programming languages, including HTML, CSS, JavaScript, Python, and Java. Users can create, edit, and save code files, with the option to download them as text files. CodeX combines robust functionality with a sleek, intuitive design, making coding effortless and enjoyable.",
  //   image: "CodeX.png",
  //   live: false,
  //   technologies: ["React", "Tailwind", "Ace Editor"],
  //   link: "https://github.com/Code-Mars/CodeX",
  //   github: "https://github.com/Code-Mars/CodeX",
  // },
];

const SkillInfo = [
  {
    title: "Frontend",
    skills: [
      "HTML",
      "CSS",
      "JavaScript",
      "React JS",
      "Redux",
      "Tailwind CSS",
      "Material UI",
      "Bootstrap",
    ],
  },
  {
    title: "Backend",
    skills: [
      "Django",
      "Django Rest Framework",
      "MySQL",
      "LLM Integration",
      "Spring Boot",
      "PostgresSQL",
    ],
  },
  {
    title: "Languages",
    skills: ["C++", "Python", "JavaScript", "TypeScript", "Java"],
  },
  {
    title: "Tools",
    skills: [
      "Git",
      "Github",
      "VS Code",
      "Thunder Client",
      "Burp Suite",
      "IntellijIdea",
      "Postman",
    ],
  },
  {
    title: "Courses",
    skills: [
      "Data Structures and Algorithms",
      "Database Management Systems",
      "Problem Solving and Computer Programming",
      "Computer Networks",
      "Computer Architecture",
      "Software Engineering Principles",
      "Operating Systems",
      "Pattern Recognition and Machine Learning",
    ],
  },
];
const socialLinks = [
  { link: "https://github.com/Arunkumarsuthari", icon: IconBrandGithub },
  {
    link: "https://www.linkedin.com/in/arunkumarsuthari",
    icon: IconBrandLinkedin,
  },
  {
    link: "https://www.instagram.com/arunkumarsuthari_",
    icon: IconBrandInstagram,
  },
  // { link: "https://www.youtube.com/channel/UC1ki6jaFvFiH_E79b9FYptw", icon: IconBrandYoutube },
  { link: "https://www.leetcode.com/arun3007", icon: IconBrandLeetcode },
];

const ExperienceInfo = [
  {
    role: "Application Developer",
    company: "Oracle",
    date: "June 2025 - Present",
    desc: "As an Application Developer at Oracle, I am responsible for developing and maintaining enterprise-grade applications. My role involves collaborating with cross-functional teams to design, implement, and optimize software solutions that meet business requirements. I focus on writing clean, efficient code, conducting thorough testing, and ensuring the scalability and performance of applications. My work contributes to enhancing user experience and driving innovation within the organization.",
    skills: ["Java", "SpringBoot", "Oracle DB", "Git"],
  },
  {
    role: "Project Intern",
    company: "Fractal Analytics",
    date: "May 2024 - July 2024",
    desc: "I worked on VAPT issues, worked on Bugs of 4 main pages and also worked in automation of testing of the project.",
    skills: [
      "React JS",
      "DjangoRestFramework",
      "Burp Client Community Edition",
      "PgAdmin",
      "Codecept JS",
    ],
  },
  {
    role: "Summer Intern",
    company: "NIT Warangal",
    date: "May 2022 - July 2023",
    desc: " Developed an algorithmic solution using MATLAB for optimizing support structures in 3D printing processes. The primary objectives were to minimize material usage and reduce print time, enhancing the efficiency of the overall printing process.",
    skills: ["MATLAB", "RRT", "PRM", "Dijkstra's Algorithm", "Geometry"],
  },
];

const EducationInfo = [
  {
    role: "Bachelor of Technology (BTech)",
    company: "Major in Mechanical and Minor in Computer Science",
    date: "Dec 2021 - May 2025",
    desc: "National Institute of Technology, Warangal",
    cgpa_or_percentage: "9.31/10",
  },
  {
    role: "Intermediate (XI and XII)",
    company: "State Board of Intermediate Education Telangana",
    date: "June 2019 - April 2021",
    desc: " Narayana Junior College, Medchal, Hyderabad",
    cgpa_or_percentage: "98/100",
  },
  {
    role: "Secondary School Certificate(SSC)",
    company: "State Board of Education Telangana",
    date: "April 2018 - May 2019",
    desc: "Krishnaveni High School, Khanapur",
    cgpa_or_percentage: "9.8/10",
  },
];
const Slugs = [
  "typescript",
  "spring",
  "javascript",
  // "dart",
  "java",
  "react",
  "django",
  // "angular",
  // "flutter",
  // "android",
  "html5",
  "css3",
  "springboot",
  // "mongodb",
  "selenium",
  // "nodedotjs",
  // "express",
  // "nextdotjs",
  // "prisma",
  "mysql",
  // "amazonaws",
  "postgresql",
  // "firebase",
  // "nginx",
  "vercel",
  "playwright",
  // "testinglibrary",
  // "jest",
  // "cypress",
  // "docker",
  "git",
  // "jira",
  "github",
  "gitlab",
  "visualstudiocode",
  "django-rest-framework",
  "intellij-idea",
  "codeceptjs",
  // "androidstudio",
  // "sonarqube",
  // "figma",
];
export {
  Info,
  ProjectInfo,
  socialLinks,
  SkillInfo,
  ExperienceInfo,
  Slugs,
  EducationInfo,
};
